config/routes.rb
Rails.application.routes.draw do

  get 'service/new/:id' => 'service#new'

  resources :website_services
  resources :service_types
  resources :places
  
  resources :places do
    resources :website_services
  end  

  

end

app/models/website_service.rb
class WebsiteService < ActiveRecord::Base
	belongs_to :place
	belongs_to :place_service
end

app/controllers/website_services_controller.rb
class WebsiteServicesController < ApplicationController
  before_action :set_website_service, only: [:show, :edit, :update, :destroy]

  # GET /website_services
  # GET /website_services.json
  def index
    @website_services = WebsiteService.all
  end

  # GET /website_services/1
  # GET /website_services/1.json
  def show
  end

  # GET /website_services/new
  def new
    @website_service = WebsiteService.new
    @place = Place.find_by_id(params[:place_id])
  end

  # GET /website_services/1/edit
  def edit
  end

  # POST /website_services
  # POST /website_services.json
  def create
    @website_service = WebsiteService.new(website_service_params)
    @place_service = PlaceService.new

    respond_to do |format|
      if @website_service.save

          @place_service.place_id = @website_service.place_id
          @place_service.service_name = @website_service.name
          @place_service.service_short_description = @website_service.description
          @place_service.service_type_id = 1  #TODO: should pass the correct service type
          @place_service.service_id = @website_service.id
          @place_service.save

        #format.html { redirect_to @website_service, notice: 'Website service was successfully created.' }
        format.html { redirect_to '/places/' + @website_service.place_id.to_s, notice: 'Service was successfully added.'}
        format.json { render :show, status: :created, location: @website_service }
      else
        format.html { render :new }
        format.json { render json: @website_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /website_services/1
  # PATCH/PUT /website_services/1.json

  def edit
    @place = Place.find_by_id(params[:place_id])
  end

  def update

   @service_details = website_service_params
   @place_service = PlaceService.find_by service_id: params[:id], service_type: 1

   #TODO: service_type should not be hard coded

    respond_to do |format|
      if @website_service.update(website_service_params)

        @place_service.service_name = @website_service.name
        @place_service.service_short_description = @website_service.description
        @place_service.service_category = ''
        @place_service.save

        format.html { redirect_to '/places/' + @website_service.place_id.to_s, notice: 'Website service was successfully updated.' }
        format.json { render :show, status: :ok, location: @website_service }
      else
        format.html { render :edit }
        format.json { render json: @website_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /website_services/1
  # DELETE /website_services/1.json
  def destroy
    PlaceService.destroy_all('service_type_id = 1 and service_id =' + params[:id].to_s)
    @website_service.destroy
    respond_to do |format|
      

      format.html { redirect_to '/places/' + @website_service.place_id.to_s, notice: 'Website service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website_service
      @website_service = WebsiteService.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_service_params
      params.require(:website_service).permit(:place_id, :redirect_url, :name, :description)
    end
end

app/helpers/website_services_helper.rb
module WebsiteServicesHelper
end

app/views/website_services/_form.html.erb
<%= form_for @website_service, :html => { :class => "form-horizontal website_service" } do |f| %>

    <% if @website_service.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@website_service.errors.count, "error") %> prohibited this website_service from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @website_service.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">

    <%= f.label :place, :class => 'control-label' %>
    <div class="controls">
      <%= @place.name %>
      <%= f.hidden_field :place_id, :value => @place.id %>
      <%= hidden_field(:place_service, :place_id, :value => @place.id) %>
      <%= hidden_field(:place_service, :service_type_id, :value => 1) %>
    </div>
    <%= error_span(@website_service[:place_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :redirect_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :redirect_url, :class => 'form-control' %>
    </div>
    <%= error_span(@website_service[:redirect_url]) %>
  </div>
  <p><p>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            website_services_path, :class => 'btn btn-default' %>

<% end %>

app/views/website_services/edit.html.erb
<%- model_class = WebsiteService -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= form_for @website_service, :html => { :class => "form-horizontal website_service" } do |f| %>

    <% if @website_service.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@website_service.errors.count, "error") %> prohibited this website_service from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @website_service.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">

    <%= f.label :place, :class => 'control-label' %>
    <div class="controls">

      <%= @place.name %>
      <%= hidden_field(:website_service, :service_id, :value => @place.id) %>
    </div>
    <%= error_span(@website_service[:place_id]) %>
  </div>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>

    <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
  </div>


  <div class="control-group">
    <%= f.label :redirect_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :redirect_url, :class => 'form-control' %>
    </div>
    <%= error_span(@website_service[:redirect_url]) %>
  </div>
  <p><p>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            website_services_path, :class => 'btn btn-default' %>

<% end %>

app/views/website_services/index.html.erb
<%- model_class = WebsiteService -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:place_id) %></th>
      <th><%= model_class.human_attribute_name(:redirect_url) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @website_services.each do |website_service| %>
      <tr>
        <td><%= link_to website_service.id, website_service_path(website_service) %></td>
        <td><%= website_service.place_id %></td>
        <td><%= website_service.redirect_url %></td>
        <td><%=l website_service.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_website_service_path(website_service), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      website_service_path(website_service),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/website_services/new.html.erb
<%- model_class = WebsiteService -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= form_for @website_service, :html => { :class => "form-horizontal website_service" } do |f| %>

    <% if @website_service.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@website_service.errors.count, "error") %> prohibited this website_service from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @website_service.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">

    <%= f.label :place, :class => 'control-label' %>
    <div class="controls">
      <%= @place.name %>
      <%= f.hidden_field :place_id, :value => @place.id %>
      <%= hidden_field(:place_service, :place_id, :value => @place.id) %>
      <%= hidden_field(:place_service, :service_type_id, :value => 1) %>
    </div>
    <%= error_span(@website_service[:place_id]) %>
  </div>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@website_service[:name]) %>
  </div>

    <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%= error_span(@website_service[:description]) %>
  </div>


  <div class="control-group">
    <%= f.label :redirect_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :redirect_url, :class => 'form-control' %>
    </div>
    <%= error_span(@website_service[:redirect_url]) %>
  </div>
  <p><p>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            website_services_path, :class => 'btn btn-default' %>

<% end %>

app/views/website_services/show.html.erb
<%- model_class = WebsiteService -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @website_service.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @website_service.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:redirect_url) %>:</strong></dt>
  <dd><%= @website_service.redirect_url %></dd>
</dl>

<%= link_to('Edit', '/places/' + params[:place_id] + '/website_services/' + params[:id] + '/edit', :class => 'btn btn-default') %>

<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              website_service_path(@website_service),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>