config/routes.rb
Rails.application.routes.draw do

  get 'service/new/:id' => 'service#new'

  resources :website_services
  resources :service_types
  resources :places
  
  resources :places do
    resources :website_services
  end  

  

end

app/models/place.rb
class Place < ActiveRecord::Base


	has_many :website_services, :dependent => :destroy
	has_many :place_services, :dependent => :destroy

	
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]



  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find_by_sql(["SELECT id, name, description, coordinate_type, coordinates, st_x(st_centroid(coordinates)) as center_lat, st_y(st_centroid(coordinates)) as center_lng  from places where id=?", params[:id]]).first
    @services = PlaceService.where("place_id = ?", params[:id])

  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
    @place = Place.find_by_sql(["SELECT id, name, description, coordinate_type, coordinates, st_x(st_centroid(coordinates)) as center_lat, st_y(st_centroid(coordinates)) as center_lng  from places where id=?", params[:id]]).first
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, :coordinate_type, :coordinates)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for @place, :html => { :class => "form-horizontal place" } do |f| %>

    <% if @place.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @place.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@place[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@place[:description]) %>
  </div>

  <input type="hidden" value="<%= @place.coordinates %>" name="place[coordinates]" id="place_coordinates">
   <br>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            places_path, :class => 'btn btn-default' %>

<% end %>

app/views/places/edit.html.erb
<%- model_class = Place -%>

<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.css' rel='stylesheet' />
<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.js'></script>
<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-geodesy/v0.1.0/leaflet-geodesy.js'></script>
<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css' rel='stylesheet' />
<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-omnivore/v0.2.0/leaflet-omnivore.min.js'></script>
<!--[if lt IE 9]>
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.ie.css' rel='stylesheet' />
<![endif]-->
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/css/font-awesome.min.css' rel='stylesheet' />
<div id="map-container">
  <div id="map-canvas"></div>
</div>


<%= render :partial => 'form' %>
  <input type="hidden" value="<%= @place.center_lat %>" id="place_center_lat">
  <input type="hidden" value="<%= @place.center_lng %>" id="place_center_lng">
<script>
L.mapbox.accessToken = 'pk.eyJ1Ijoiamp1bmUwMDEiLCJhIjoiMDBkOTZlMmRiZTQ1M2ZiZTdmOTA5YjNmYWU0NmM4MGEifQ.2R72JqPjQ03-LgYMWKARKw';
var coordinate = $(place_coordinates).val();
var coordinateCenterLng = $(place_center_lng).val();
var coordinateCenterLat = $(place_center_lat).val();

var map = L.mapbox.map('map-container', 'mapbox.streets')
    .setView([coordinateCenterLng, coordinateCenterLat], 14);
   

var drawnItems = new L.FeatureGroup();
//var featureLayer = L.mapbox.featureLayer(coordinate).addTo(map);
var featureLayer = omnivore.wkt.parse(coordinate).addTo(map);


var drawControl = new L.Control.Draw({
  edit: {
    featureGroup: featureLayer
  },
  draw: {
      polygon: false,
      polyline: false,
      rectangle: false,
      circle: false,
      marker: false
  }
});
map.addControl(drawControl);

map.on('draw:edited', showPolygonAreaEdited);

function showPolygonAreaEdited(e) {
  e.layers.eachLayer(function(layer) {
    showPolygonArea({ layer: layer });
  });
}
function showPolygonArea(e) {
  drawnItems.clearLayers();
  drawnItems.addLayer(e.layer);
  e.layer.bindPopup((LGeo.area(e.layer) / 100000).toFixed(2) + ' km<sup>2</sup>');
  var placeshape = toWKT(e.layer)
  $(place_coordinates).val(placeshape)
  e.layer.openPopup();
}

function toWKT(layer) {
    var lng, lat, coords = [];
    if (layer instanceof L.Polygon || layer instanceof L.Polyline) {
        var latlngs = layer.getLatLngs();
        for (var i = 0; i < latlngs.length; i++) {
        latlngs[i]
        coords.push(latlngs[i].lng + " " + latlngs[i].lat);
          if (i === 0) {
            lng = latlngs[i].lng;
            lat = latlngs[i].lat;
          }
  };
        if (layer instanceof L.Polygon) {
            return "POLYGON((" + coords.join(",") + "," + lng + " " + lat + "))";
        } else if (layer instanceof L.Polyline) {
            return "LINESTRING(" + coords.join(",") + ")";
        }
    } else if (layer instanceof L.Marker) {
        return "POINT(" + layer.getLatLng().lng + " " + layer.getLatLng().lat + ")";
    }
}

</script>

app/views/places/index.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:coordinates) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= link_to place.id, place_path(place) %></td>
        <td><%= place.name %></td>
        <td><%= place.coordinates %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_place_path(place), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      place_path(place),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_place_path,
            :class => 'btn btn-primary' %>

app/views/places/new.html.erb
<%- model_class = Place -%>

<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.css' rel='stylesheet' />
<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.js'></script>
<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-geodesy/v0.1.0/leaflet-geodesy.js'></script>

<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css' rel='stylesheet' />
<!--[if lt IE 9]>
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.ie.css' rel='stylesheet' />
<![endif]-->
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/css/font-awesome.min.css' rel='stylesheet' />


<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

<div id="map-container">
  <div id="map-canvas"></div>
</div>

<script>
L.mapbox.accessToken = 'pk.eyJ1Ijoiamp1bmUwMDEiLCJhIjoiMDBkOTZlMmRiZTQ1M2ZiZTdmOTA5YjNmYWU0NmM4MGEifQ.2R72JqPjQ03-LgYMWKARKw';
var map = L.mapbox.map('map-container', 'mapbox.streets')
    .setView([40.7903, -73.9597], 16);
 L.control.locate().addTo(map);

var featureGroup = L.featureGroup().addTo(map);
var drawControl = new L.Control.Draw({
  edit: {
    featureGroup: featureGroup
  },
  draw: {
    polygon: true,
    polyline: false,
    rectangle: false,
    circle: false,
    marker: false
  }
}).addTo(map);

map.on('draw:created', showPolygonArea);
map.on('draw:edited', showPolygonAreaEdited);

function showPolygonAreaEdited(e) {
  e.layers.eachLayer(function(layer) {
    showPolygonArea({ layer: layer });
  });
}
function showPolygonArea(e) {
  featureGroup.clearLayers();
  featureGroup.addLayer(e.layer);
  e.layer.bindPopup((LGeo.area(e.layer) / 100000).toFixed(2) + ' km<sup>2</sup>');
  var placeshape = toWKT(e.layer)
  $(place_coordinates).val(placeshape)
  e.layer.openPopup();
}
function toWKT(layer) {
    var lng, lat, coords = [];
    if (layer instanceof L.Polygon || layer instanceof L.Polyline) {
        var latlngs = layer.getLatLngs();
        for (var i = 0; i < latlngs.length; i++) {
        latlngs[i]
        coords.push(latlngs[i].lng + " " + latlngs[i].lat);
          if (i === 0) {
            lng = latlngs[i].lng;
            lat = latlngs[i].lat;
          }
  };
        if (layer instanceof L.Polygon) {
            return "POLYGON((" + coords.join(",") + "," + lng + " " + lat + "))";
        } else if (layer instanceof L.Polyline) {
            return "LINESTRING(" + coords.join(",") + ")";
        }
    } else if (layer instanceof L.Marker) {
        return "POINT(" + layer.getLatLng().lng + " " + layer.getLatLng().lat + ")";
    }
}

</script>

app/views/places/show.html.erb
<%- model_class = Place -%>
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.css' rel='stylesheet' />
<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.js'></script>
<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-geodesy/v0.1.0/leaflet-geodesy.js'></script>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

  <input type="hidden" value="<%= @place.coordinates %>" name="place[coordinates]" id="place_coordinates">
  <input type="hidden" value="<%= @place.center_lat %>" id="place_center_lat">
  <input type="hidden" value="<%= @place.center_lng %>" id="place_center_lng">

<%= link_to t('.back', :default => t("helpers.links.back")),
              places_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_place_path(@place), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              place_path(@place),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>


<div id="map-container">
  <div id="map-canvas"></div>
</div>

<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-omnivore/v0.2.0/leaflet-omnivore.min.js'></script>
<script>
L.mapbox.accessToken = 'pk.eyJ1Ijoiamp1bmUwMDEiLCJhIjoiMDBkOTZlMmRiZTQ1M2ZiZTdmOTA5YjNmYWU0NmM4MGEifQ.2R72JqPjQ03-LgYMWKARKw';

var center_coordinates_x = $(place_center_lat).val()
var center_coordinates_y = $(place_center_lng).val()
var coordinates = $(place_coordinates).val()
var map = L.mapbox.map('map-container', 'mapbox.streets')
  .setView([center_coordinates_y, center_coordinates_x], 14);
omnivore.wkt.parse(coordinates).addTo(map);
    
</script>
<br><br>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @place.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @place.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:coordinates) %>:</strong></dt>
  <dd><%= @place.coordinates %></dd>
  
  <dt><strong>Services</dt>
    <dd><%= link_to 'Add Service', '/service/new/' + params[:id] %></dd>
    <br>
    <dd>
      <ul class="list-group">
      <% @services.each do |service| %>
        <li class="list-group-item">
        <%= link_to get_service_name(service.service_id, service.service_type_id), '/places/' + @place.id.to_s + "/website_services/" + service.service_id.to_s %>
        
        </li>
      <% end %>
       </ul>
    </dd>

</dl>